dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36

    - python: "3.6"
      env: TOXENV=flake8

install:
  - pip install tox
  - pip install pipenv
  - pipenv install --dev --system --skip-lock

script:
  - tox

after_success:
  - coverage xml -o coverage.xml
  - python-codacy-coverage -r coverage.xml

notifications:
  email: false
